baseURL = "https://codeblind.ai"
title = ""

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]


# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration

[languages]
[languages.en]
languageName ="English"
# Weight used for sorting.
weight = 1
[languages.en.params]
title = "Goldydocs"
description = "A Docsy example site"

# [languages.pt]
# languageName ="Português"
# contentDir = "content/pt"
# [languages.pt.params]
# title = "Goldydocs"
# description = "Um site de exemplo Docsy"
# time_format_default = "2006.01.02"
# time_format_blog = "2006.01.02"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax = "true"

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]


[params]
copyright = "Copyright Code Blind LLC"
privacy_policy = "https://policies.google.com/privacy"
github_repo = "https://github.com/josephbarnett/codeblind.ai"
site_app  = "https://app.codeblind.ai/login"
# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "c6fbc2e4fe191475a"

# current release branch. Never is rc.
release_branch = "release-1.38.0"
# the main version. Never is rc.
release_version = "1.38.0"

# shown for production
supported_k8s = ["1.26", "1.27", "1.28"]
k8s_api_version = "1.27"
gke_example_cluster_version = "1.27"
aks_example_cluster_version = "1.28.0"
eks_example_cluster_version = "1.28"
minikube_example_cluster_version = "1.27.6"
# shown in development (or the next versions that will be supported)
dev_supported_k8s = ["1.26", "1.27", "1.28"]
dev_k8s_api_version = "1.27"
dev_gke_example_cluster_version = "1.27"
dev_aks_example_cluster_version = "1.28.0"
dev_eks_example_cluster_version = "1.28"
dev_minikube_example_cluster_version = "1.27.6"

# example tag
example_image_tag = "us-docker.pkg.dev/codeblind/examples/simple-server:0.27"

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false


# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/josephbarnett/codeblind.ai/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/josephbarnett/codeblind.ai/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Discord"
	url = "https://discord.com/invite/WmtCSMNV"
	icon = "fab fa-discord"
desc = "Chat with other project users in #users"
[[params.links.user]]
	name = "User mailing list"
	url = "https://groups.google.com/forum/#!forum/codeblind-discuss"
	icon = "fa fa-envelope"
	desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="X"
	url = "https://twitter.com/codeblind"
	icon = "fab fa-x-twitter"
	desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name ="Community Meetings"
	url = "https://github.com/josephbarnett/"
	icon = "fab fa-youtube"
	desc = "Live discussion of new features and issues, see the <a href=\"https://github.com/josephbarnett/codeblind.ai/blob/main/CONTRIBUTING.md#community-meetings\">calendar</a> or <a href=\"https://groups.google.com/forum/#!forum/codeblind-discuss\">mailing list</a> for details"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/josephbarnett/"
	icon = "fab fa-github"
	desc = "Development takes place here!"
[[params.links.developer]]
	name = "Resume"
	url = "https://github.com/josephbarnett/"
	icon = "fab fa-linkedin"
	desc = "Developers"
[[params.links.developer]]
	name ="Facebook"
	url = "https://github.com/josephbarnett/"
	icon = "fab fa-facebook"
	desc = "facebook community"
[[params.links.developer]]
	name ="Contact"
	url = "https://github.com/josephbarnett/codeblind.ai"
	icon = "fab fa-whatsapp"
	desc = "contact us"

[security.funcs]
  getenv = ['^HUGO_', '^CI$', 'RELEASE_BRANCH', 'HUGO_ENV', 'RELEASE_VERSION']

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
